### ISSUE TITLE
Warehouse is broken on latest RC version

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#186]
With 2.3.1.6852 I get the following error printed in the console:

```
puppet.js:285 Uncaught Error: PuppetJs JSON response error. Server responded with error 404 Not Found

URI not found: PATCH /api/servermodel/091491ff-2a00-45cf-98b3-fa0eb9d0ea4e/D2BAD2A5F692166610000030 
    at XMLHttpRequest.req.onload (puppet.js:285)
```

![brokenwarehouse](https://user-images.githubusercontent.com/19392292/28510604-a5976718-7049-11e7-80d9-589667cc5737.gif)

Also, this is in the log:

```
Starcounter.XSON.JsonPatchException: Unknown namespace in path. Patch: '{"op":"replace","path":"/Databases/0/Applications/2/Delete$","value":1}'. Property: 'Databases'.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 161
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 550
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 478
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 376
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterFullModelApi>b__6_2(String data, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 143
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
Patch={"op":"replace","path":"/Databases/0/Applications/2/Delete$","value":1}
CurrentProperty=Databases
Severity=1
HResult=-2146233088
```

I've tried it on two different machines and it's the same error every time.

Downgrading to 2.3.1.6769 fixes the problem

**Comment by chrhol** [comment]
Probably due to the latest changes with allowing blending on the root level by namespacing the root. A similar problem was found in the Administrator, which uses some hardcoded paths. 

The solution there was to disable namespaces when the session is created (see https://github.com/Starcounter/Level1/issues/4017#issuecomment-310977866) or alternatively hardcode the root namespace (see the next comment from the previous link).

Unfortunately I'm supposed to be on vacation (only here to finish up one last issue that was delayed and that needs to be finished) so I will not have time to fix it.

**Comment by warpech** [comment]
I will do an investigation. I hope someone else can fix this today.

**Comment by warpech** [comment]
Actually there are more problems. Trying to **start** a DB results in an error as well: 

```
Starcounter.XSON.JsonPatchException: Unknown namespace in path. Patch: '{""op"":""replace"",""path"":""/Databases/0/Start$"",""value"":1}'. Property: 'Databases'.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 161
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 550
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 478
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 376
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterFullModelApi>b__6_2(String data, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 143
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6658\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
Patch={""op"":""replace"",""path"":""/Databases/0/Start$"",""value"":1}
CurrentProperty=Databases
Severity=1
HResult=-2146233088
```

@ubbeK perhaps two of us can fix it?

**Comment by warpech** [comment]
Since both @chrhol and @ubbeK are on vacation, I will try to fix this with @alemoi.

**Comment by bouguila** [comment]
Facing same issue staring whatever app from warehouse with latest RC.

**Comment by warpech** [comment]
The issue is solved by the above commits, tested locally and using @alemoi's build. Please reopen if happens again starting from the next nightly build.

**Comment by bouguila** [comment]
i'm still having some problems even with  2.3.1.6860 release 
![error](https://user-images.githubusercontent.com/12608524/28568362-d4c59d9c-7135-11e7-8c37-47c72afb305b.gif)

**Comment by bouguila** [comment]
@warpech any idea?

**Comment by warpech** [comment]
@alemoi could you pls take a look?

@bouguila pls paste the error messages that you see in the Log. Notice that in the same second there were more errors reported, as I can see on your screengrab.

**Comment by bouguila** [comment]
ScErrServerCommandFailed (SCERR10011): The operation "Attempting to restart code host for default" failed.
Version: 2.3.1.6860.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost "default. Version: 2.3.1.6860. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047. 
   at Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 333
   at Starcounter.Server.DatabaseEngine.RestartCodeHost(ICommandProcessor processor, Int32 terminatingCodeHostProcessId, DatabaseInfo databaseInfo) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 462
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047

System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost "default.
Version: 2.3.1.6860.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2047.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 63
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 135
   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Bootstrap\Control.cs:line 216
   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Bootstrap\Control.cs:line 55
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2047

**Comment by alemoi** [comment]
So its only when starting third app?

**Comment by bouguila** [comment]
yes.. its happening only with images app for me.

**Comment by habib535** [comment]
Hi, After upgrading to latest RC version, the same error is appearing for me with **Sign In** app.

**Comment by alemoi** [comment]
@habib535 so I can just attempt to start Sign In app alone? Or after some other?

**Comment by habib535** [comment]
yes just add Sign In from warehouse and hit start to reproduce the issue.

**Comment by bouguila** [comment]
fixed the problem with an upgrade to the the versions of apps their selfs.

**Comment by habib535** [comment]
thanks @bouguila

**Comment by alemoi** [comment]
@bouguila can you please provide more details on how the issue was fixed in the updated apps?

**Comment by bouguila** [comment]
@alemoi setting TreatWarningsAsErrors fixed this issue
