### ISSUE TITLE
Error in 2.4.0.2931 (2.4.0.2917 OK)

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#243]
```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Starcounter.QueryProcessor
  StackTrace:
       at Starcounter.Internal.sccrud.star_crud_GetTypeId(UInt64 context_handle, String class_name, UInt64& type_id)
       at Starcounter.Binding.TableDef.InitializeCrudHandles()
       at Starcounter.Binding.TableDef.ConstructTableDef(STARI_LAYOUT_INFO tableInfo, Boolean resolveNamesAndHandles)
       at Starcounter.Db.LookupTable(String name) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter\Db.cs:line 103
       at Starcounter.Hosting.Package.<>c__DisplayClass23_0.<CreateOrUpdateDatabaseTable>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 445
       at Starcounter.Db.TransactAsync(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter\Db.cs:line 314
       at Starcounter.Db.Transact(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter\Db.cs:line 427
       at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 448
       at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 352
       at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 201
       at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 136
       at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 50
       at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-8461\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 90
  InnerException: 
```

**Comment by k-rus** [comment]
Thank you for reporting.

It seems to me that this version was published by mistake.

**Comment by k-rus** [comment]
However, this build contains changes, which are pushed into develop and expected to be available this night.

**Comment by k-rus** [comment]
The reported build is removed, since it was a private build unintended for publishing. However, since the changes was merged into develop, we will investigate and try to fix it before nightly will run. So no broken version of Starcounter is produced.

**Comment by k-rus** [comment]
The changes were reverted and should not present in coming nightly build. So the error should not appear. Thus I close the issue.
We continue work internally and might need to reproduce the issue internally. @SenerDemiral may we contact you if we will need help to reproduce it, i.e., get to know the set up?

**Comment by SenerDemiral** [comment]
No doubt.  Whenever you want.

**Comment by SenerDemiral** [comment]
@k-rus 2.4.0.2951 is OK.

**Comment by k-rus** [comment]
> @k-rus 2.4.0.2951 is OK.

Thanks. Good. Reversion of changes worked correctly.

**Comment by alexanderstc** [comment]
@SenerDemiral I'll roll back some of recent commits, please stand by.

**Comment by alexanderstc** [comment]
@SenerDemiral could you provide a reproducible setup for me to test on my machine?

**Comment by alexanderstc** [comment]
Meanwhile i'm building 2.4.0.3133.

**Comment by alexanderstc** [comment]
2.4.0.3133 is ready, if you can access it.
Otherwise 2.4.0.3134 or later will be ready in a few hours.

**Comment by SenerDemiral** [comment]
Only 2.4.0.3129 is visible to me!

**Comment by alexanderstc** [comment]
You'll have to wait longer then.

**Comment by alexanderstc** [comment]
For 3134 or later builds.

**Comment by SenerDemiral** [comment]
OK

**Comment by alexanderstc** [comment]
3134 is ready.

**Comment by SenerDemiral** [comment]
I'm checking.

**Comment by SenerDemiral** [comment]
Still same error message!

**Comment by alexanderstc** [comment]
Will roll back further.

**Comment by alexanderstc** [comment]
Building, ETA is at least 1hr40min from now.

**Comment by SenerDemiral** [comment]
OK

**Comment by alexanderstc** [comment]
3137 is ready.

**Comment by SenerDemiral** [comment]
Same error :(

**Comment by alexanderstc** [comment]
I can't revert any further on main build without consulting with others,
what I could do now is to make a separate build, futher reverted, just for us to try and find out the point of failure.
I will have to upload it to you somehow.

**Comment by alexanderstc** [comment]
Do you want me to do that?

**Comment by SenerDemiral** [comment]
Never mind, it's not urgent.

**Comment by SenerDemiral** [comment]
3139 has same error too.

**Comment by alexanderstc** [comment]
Supposed to.

**Comment by SenerDemiral** [comment]
There is no `C:\Program Files\Starcounter\ScAnalyzeReference.psproj`
but there is  `C:\Program Files\Starcounter\ScAnalyzeOnly.psproj`

**Comment by per-samuelsson** [comment]
This one seem to be a bug introduced by me. I'm on it. Think it's a file that was not whitelisted in installer. Hang on.

(Remember, 2.4 is bleeding edge)

**Comment by per-samuelsson** [comment]
> This one seem to be a bug introduced by me. I'm on it. Think it's a file that was not whitelisted in installer. Hang on.

Fixed, merged and pushed: https://github.com/Starcounter/level1/commit/69c7184c43b13ff3f107ff47b0cfe0244ac5aa54. Will be activated in next nightly. Thanks for reporting @SenerDemiral. Let us know if you need a build faster than that and we can make a custom one for you.

**Comment by SenerDemiral** [comment]
Thank you, no need. I can wait.

**Comment by SenerDemiral** [comment]
v2.4.0.3148
Compiled successfully, but when run, exits with the code below.
```
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\sccode.exe'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.Internal.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.Logging.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.Hosting.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.ErrorCodes.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.QueryProcessor.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.Apps.JsonPatch.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.Hypermedia.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.REST.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.UriMatcher.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.BitsAndBytes.Unsafe.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.XSON.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.PrologFacade.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\SwiPLcs.standard.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.BindingInterfaces.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Token'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Token.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.SetSpecifier'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.SetSpecifier.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.MetaData'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.MetaData.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Configuration'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Configuration.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.TypeIdsMeta'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.TypeIdsMeta.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Vacuum'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.Vacuum.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.DataType'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.DataType.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.DbPrimitiveType'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.DbPrimitiveType.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.MapPrimitiveType'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.MapPrimitiveType.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.ClrPrimitiveType'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.ClrPrimitiveType.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Table'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Table.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.RawView'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.RawView.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.VMView'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.VMView.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.ClrClass'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.ClrClass.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Member'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Member.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Column'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Column.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.RawColumn'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.RawColumn.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.ReferenceRawColumn'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Internal.Metadata.ReferenceRawColumn.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Property'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Property.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.CodeProperty'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.CodeProperty.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.MappedProperty'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.MappedProperty.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Index'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.Index.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.IndexedColumn'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'gen.Starcounter.Metadata.IndexedColumn.dll'. 
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Cannot find or open the PDB file.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Starcounter.BitsAndBytes.Common.dll'. Symbols loaded.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\Newtonsoft.Json.dll'. Cannot find or open the PDB file.
0.11 Starcounter.Host.Loader:Loader started.
0.0 Starcounter.Host.AssemblyResolver:Resolving application: C:\Starcounter\Personal\Temp\tMax14\tMax14-20170723T192142812\weaver\D56AED3C09D8E7A9AAE5B8A634CF7F3AE3C3A466\tMax14web.exe
0.0 Starcounter.Host.AssemblyResolver:Loading assembly tMax14web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from C:\Starcounter\Personal\Temp\tMax14\tMax14-20170723T192142812\weaver\D56AED3C09D8E7A9AAE5B8A634CF7F3AE3C3A466\tMax14web.exe
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Starcounter\Personal\Temp\tMax14\tMax14-20170723T192142812\weaver\D56AED3C09D8E7A9AAE5B8A634CF7F3AE3C3A466\tMax14web.exe'. Symbols loaded.
127.5833 Starcounter.Host.Loader:Schema verified and loaded.
127.6868 Starcounter.Host.Loader:Package created.
127.8460 Starcounter.Host.Loader:Target assembly loaded.
128.5582 Starcounter.Host.Loader:Package started.
'sccode.exe' (CLR v4.0.30319: sccode.exe): Loaded 'C:\Program Files\Starcounter\FasterThanJson.dll'. Symbols loaded.
The program '[1828] sccode.exe' has exited with code -531431422 (0xe0530002).
```

**Comment by k-rus** [comment]
@per-samuelsson Can you look at it?

**Comment by per-samuelsson** [comment]
> @per-samuelsson Can you look at it?

Sure.

@SenerDemiral 

Thanks for reporting that!

I wonder if there is something in the project setup that is wrong. Is the project you are running one you created in 2.3? Or are you running a plain `.cs` file, i.e. `star myapp.cs`?

Anywhere I can get access to your application so I can set it up and try it?

**Comment by SenerDemiral** [comment]
DB created on v2.4.
In 2.4.0.3062 DB Tables are accessible but not  >2.4.0.3062.

I create new empty project and added module reference, and run.
On Administrator SQL
```select * from ClrClass``` 
doesn't show my tables.

GitHub: [https://github.com/SenerDemiral/tMax14web](url)

**Comment by per-samuelsson** [comment]
OK, thanks @SenerDemiral, that should be enough for now. I'll give it a while to see if I can understand what is going on.

**Comment by per-samuelsson** [comment]
![image](https://user-images.githubusercontent.com/2902045/31113649-8f23c1d0-a81a-11e7-89f9-37010d43991a.png)

Seem to work. But I might be cheating. Recreated like this:

1. Created new, empty database, i.e. `star new db` (after `staradmin delete db`).
2. Running only a single app: `star tMax14web.exe`.

Also, tested on a local build on a code-base that might be a day old or so. I'll rebuild a new version of latest code and test again. Meanwhile, let me know if your setup is different.

**Comment by SenerDemiral** [comment]
I used already created DB on <= v2.4.0.3062.
Maybe I should create DB for >3062 as you do.

**Comment by k-rus** [comment]
> I used already created DB on <= v2.4.0.3062.

So the problem is observed if a database created with a previous version of Starcounter is used, right?

**Comment by SenerDemiral** [comment]
Yes, but created with 2.4

**Comment by per-samuelsson** [comment]
> Yes, but created with 2.4

Aha, ok. That might be it. Since we are pushing quite heavy changes at the moment, and we might break things between I guess.

I'm not sure about our policy here tbh. If you create a database in 2.3 and want to use it in 2.4, you will have to rebuild it (i.e. unload/reload) once 2.4 become stable. That's for sure, and something we need to leave a guarantee that it will work (obv).

If you create a database in one version of 2.4 and it doesn't work in a later, I'm not sure we can support that really, since 2.4 is really bleeding edge.

@k-rus, what's your view on that?

**Comment by per-samuelsson** [comment]
> Maybe I should create DB for >3062 as you do.

Can you try that and see if it works at least? You don't have to delete the default one just yet (if u have something you like to keep in it), just do this instead:

```
star -d=somenameyouchoose tMax14web.exe
```

and a new emtpy database will be created on the fly.

**Comment by per-samuelsson** [comment]
>  I'll rebuild a new version of latest code and test again.

Works equally good on build of latest code too (and that code is latest nightly).

**Comment by SenerDemiral** [comment]
By the way, I admire your ambition to solve problems. How a discipline / passion!

**Comment by k-rus** [comment]
> I'm not sure about our policy here tbh. If you create a database in 2.3 and want to use it in 2.4, you will have to rebuild it (i.e. unload/reload) once 2.4 become stable. That's for sure, and something we need to leave a guarantee that it will work (obv).
> 
> If you create a database in one version of 2.4 and it doesn't work in a later, I'm not sure we can support that really, since 2.4 is really bleeding edge.
> 
> @k-rus, what's your view on that?

If we don't say explicit that reload is required, then it should not be required. Metalayer is fixed to allow seamless migration. I am not sure if it is so for migrating from 2.3 to 2.4. However, it should not be a problem between different versions of 2.4.

**Comment by alexanderstc** [comment]
> . I am not sure if it is so for migrating from 2.3 to 2.4. 

Metalayer is recently testes to support that seamlessly.
Bugs are still oossible, of course.

**Comment by SenerDemiral** [comment]
As you said, it worked on newly created DB.
I will try to unload the data from old and load to the new one using 2.4.0.3148.
Should I use v3062 to unload and v3148 to load?

**Comment by per-samuelsson** [comment]
> As you said, it worked on newly created DB.

That's good at least. Thanks for verifying.

> I will try to unload the data from old and load to the new one using 2.4.0.3148.

If you actually do keep real data in there, we can of course help you with it. If so, I want to spend time finding out why you couldn't start app in the later version, while an earlier version of 2.4 worked.

> Should I use v3062 to unload and v3148 to load?

I guess so, yeah. But maybe I should try find real cause of your trouble instead? (see above)

**Comment by SenerDemiral** [comment]
For now I have no valuable data.
But I should see unload/reload works as expected in such situations.

**Comment by SenerDemiral** [comment]
@per-samuelsson 
Unload with v3165 (Last version)
```
StarDump -v

StarDump application version:    0.2.2
SQLite dump format version:      0.0.2

Configuration settings:
    Verbose: 4
    DatabaseName: tMax14
    FileName: C:\Starcounter\YDK\tMax14.sqlite3
    SkipColumnPrefixes: [__]
    SkipTablePrefixes: []
    SkipTables: []
    UnloadTables: []
    InsertRowsBufferSize: 200
    InsertObjectNoOffset: 0
    ReassignObjectNo: False

```
Gives following error.
```
Starcounter.Core.ScErrTypeNotFound: ScErrTypeNotFound (SCERR15003): There is no type in the database for the given type name. 
Table not found by incomplete reverse id Starcounter.Metadata.RawView.
 In query:SELECT t FROM "Starcounter.Metadata.RawView" t
   at Starcounter.Core.Database.SQLEnumerator`1.System.Collections.IEnumerator.MoveNext()
   at StarDump.Core.Unload.SelectTables(UInt64 dbHandle) in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 296
   at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 62
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 116
   at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
   at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump\CommandLineInterface.cs:line 182
```

**Comment by SenerDemiral** [comment]
@per-samuelsson 
Tested with v3062 (Working) uses same StarDump version (no difference between 3062 and 3165)  and gives same error message!

**Comment by SenerDemiral** [comment]
StarDump unload have same error on newly created DB. (v2.4.0.3165)
I think, StarDump has a problem on v2.4!

**Comment by k-rus** [comment]
> Gives following error.
> 
> Starcounter.Core.ScErrTypeNotFound: ScErrTypeNotFound (SCERR15003): There is no type in the database for the given type name. 
> Table not found by incomplete reverse id Starcounter.Metadata.RawView.
>  In query:SELECT t FROM "Starcounter.Metadata.RawView" t
>    at Starcounter.Core.Database.SQLEnumerator`1.System.Collections.IEnumerator.MoveNext()
>    at StarDump.Core.Unload.SelectTables(UInt64 dbHandle) in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 296
>    at StarDump.Core.Unload.<>c__DisplayClass12_0.<Run>b__0() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 62
>    at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
>    at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
>    at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
>    at StarDump.Core.Unload.Run() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\Unload.cs:line 116
>    at StarDump.Core.CommandInterface.Unload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump.Core\CommandInterface.cs:line 78
>    at StarDump.CommandLineInterface.<>c__DisplayClass9_1.<AddUnloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-9116\StarDump\src\StarDump\CommandLineInterface.cs:line 182

Thank you. This is a bug in StarDump to qualify entire identifier chain in SQL. @miyconst can you look at it?

**Comment by miyconst** [comment]
@SenerDemiral, Starcounter `2.4` is in development stage, please understand this. Unfortunately StarDump is not yet compatible with `2.4`, but there is working in progress.

**Comment by SenerDemiral** [comment]
Yes I understand.
Never mind, I just try to help you.

**Comment by per-samuelsson** [comment]
@SenerDemiral 

Thanks for spending time providing us with valuable input. We have on ongoing discussion of how to best tackle cases like this, and with the aim to reach an highest-possible support level, based on our resources and in sync with our different versions. 

In LTS releases / "stables", it's simple: we provide full support, always. In bleeding-edge, we need a little more time to figure out a realistic schedule.

We're going to give that discussion even more prio within just a few days. Thanks for being patient. We know it can be a pain from time to time. Rest assure we'll do our best to help you out as much as possible going forward.

**Comment by SenerDemiral** [comment]
Thanks to all of you.

**Comment by Mackiovello** [comment]
It seems like this was answered, please reopen if I'm wrong.
