### ISSUE TITLE
⏰ Response filters not working in SC 2.4

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#338]
In last SC 2.4.0.4111 middlewares is not working.

In the example below the request filter is called when I call `/app4` URI, but the response filter is not.

```csharp
Application.Current.Use((Request request, Response response) =>
{
    return null;
});

Application.Current.Use((Request request) =>
{
    return null;
});

Handle.GET("/app4", () => "success");
```

**Comment by per-samuelsson** [comment]
There was some recent issue that was worked on, that addressed something with response filters. Can't really seem to find it though. Maybe that could have caused some breakage.

**Comment by Mihaiii** [comment]
^ I have the same problem with 2.4.0.3854 so it's probably not that recent.
I wanted to try with 2.4.0.3238, but current `master-2.4` branch of Website app (this is what I'm interested in) doesn't work with it.
Now I'm looking into finding some intermediate version.

**Comment by warpech** [comment]
@miyconst, @alemoi can you help? It is urgent because Flexovital cannot use WebsiteEditor/WebsiteProvider without a fix for this.

**Comment by miyconst** [comment]
Unfortunately the only thing I can do is push @alemoi.

**Comment by alemoi** [comment]
Unfortunately I can check it earliest tomorrow.

**Comment by alemoi** [comment]
I found a missing merge in git that I just fixed. Tested and should work in `develop`. Closing the issue.

**Comment by Mihaiii** [comment]
Thanks!
The problem in the first message is probably solved, but when I run Website app on `master-2.4` with SignIn app on `master-2.4` and with CompositionProvider on `master-2.4`, I still can't see the SignIn icon when I access `http://localhost:8080/websiteeditor`.

@Starcounter/webplatformteam Could you please confirm?

**Comment by PatrykSzwer** [comment]
I do NOT confirm that. I've run everything at `2.4` branches and it looks correct:
![image](https://user-images.githubusercontent.com/25042256/33989628-706eb394-e0c8-11e7-9091-3e6f410169b5.png)

Did You called `websiteeditor/resetdata` after switching to master-2.4 branch?

**Comment by Mihaiii** [comment]
I was on a clean DB, but yes, everything is ok after calling `websiteeditor/resetdata`.
This will work for me, but it's strange that it didn't worked on a clean db.

Thanks!

**Comment by PatrykSzwer** [comment]
@Mihaiii could You try to make reproduction? Maybe It's an issue that we should take care of.

**Comment by Mihaiii** [comment]
Done: https://github.com/Starcounter/Website/issues/295 .
