### ISSUE TITLE
scTrayIcon throws an error on Windows startup

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#373]
It shows "Starcounter service error: One or more errors occurred" error notification on Windows startup and stays in the system tray with "Connecting..." status (colored in gray).

The issue looks similar to https://github.com/Starcounter/Home/issues/370 and appears after installing both 2.3.2 and 2.4 SC versions.
I installed it in **developer mode** on 3 different machines and on all of them I have the same issues.

**Comment by iqbalskd** [comment]
Its failing making a web request to the server, it fails on the following line: 
https://github.com/Starcounter/level1/blob/d31c689b1dd80f871b882e424944196cec3308b2/src/Starcounter.Internal/Rest/Http.cs#L147

It throws following exception:
```
No connection could be made because the target machine actively refused it 127.0.0.1:8181
```
@ubbeK @alemoi

**Comment by alemoi** [comment]
Are you able to make the same REST request manually. Because there is no magic about the Http client, it just uses `HttpClient` underneath.

**Comment by iqbalskd** [comment]
> Are you able to make the same REST request manually?

Yeah its working fine when the server is running, looks like the server does not start at windows logon, I will further dig into it.

**Comment by un-tone** [comment]
> looks like the server does not start at windows logon

And it should not if it is installed in developer mode.

**Comment by iqbalskd** [comment]
> And it should not if it is installed in developer mode.

One thing that I noticed though, on clicking the `Stop Server` menu item stops the server but another thread keeps browsing localhost and ends up with the same error mentioned above, and the `Start Server` menu item does not enable again.

**Comment by iqbalskd** [comment]
Fixed the issue and merged the changes

**Comment by un-tone** [comment]
The error is gone, but it still shows the notification icon

> stays in the system tray with "Connecting..." status (colored in gray)

Is it required to have this?

**Comment by iqbalskd** [comment]
This is a thread synchoronization related issue, which I am gonna re-write using Tasks which has better support for multi-threading.
