### ISSUE TITLE
What is wrong with download page since 25 of April?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#408]

**Comment by Mackiovello** [comment]
We have some trouble with our download server. It's fixed now though, all the versions that should be available are available. Don't hesitate to create a new issue if you face a problem again.

**Comment by SenerDemiral** [comment]
It is not fixed though
```
The download is not available at the moment. Please try again later.

**Comment by Mackiovello** [comment]
You're completely right. Reopening

**Comment by SenerDemiral** [comment]
It is working now.
